name: synoptic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - git

  # Tools
  # -----
  - cartopy
  - geopandas
  - h5py
  - jupyter
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - requests
  - scipy
  - toml
  - xarray

  # Formatter and Testing
  # ---------------------
  - black
  - isort
  - pylint
  - pytest

  # Documentation
  # -------------
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme # PyData Sphinx Theme (i.e, Numpy, Pandas, MetPy)
  - sphinx-panels # Add bootstrap elements to Sphinx
  - recommonmark
  - sphinx-markdown-tables
  - autodocsumm
  - sphinx-autosummary-accessors # pandas and xarray accessor docs
  - latexmk
  - myst-parser
  - linkify-it-py

  #- pip:
    # Development Version from GitHub
    #- git+https://github.com/blaylockbk/SynopticPy.git

    # Or, latest release from PyPI
    #- SynopticPy

    # Borrow some tools from Brian's garage
    #- git+https://github.com/blaylockbk/Carpenter_Workshop.git


  ## Or, clone the repo and do `pip install -e .`
